# Generated by Django 3.2 on 2022-04-13 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('kind', models.CharField(blank=True, max_length=50, null=True)),
                ('desexing', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('hair_loss', models.CharField(blank=True, max_length=50, null=True)),
                ('bark_term', models.CharField(blank=True, max_length=50, null=True)),
                ('activity', models.CharField(blank=True, max_length=50, null=True)),
                ('person_personality', models.CharField(blank=True, max_length=50, null=True)),
                ('adoptation_status', models.CharField(blank=True, max_length=50, null=True)),
                ('introduction', models.CharField(blank=True, max_length=1024, null=True)),
                ('approval', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dog',
            },
        ),
    ]
